field.widget.settings.strawberryfield_webform_inline_widget:
  type: config_object
  label: 'Webform Inline Widget Schema'
  mapping:
    placeholder:
      type: string
      label: 'Placeholder'
    webform_id:
      type: string
      label: 'Webform ID'
    rows:
      type: integer
      label: 'Rows'
field.widget.settings.strawberryfield_webform_widget:
  type: config_object
  label: 'Webform Inline Widget Schema'
  mapping:
    placeholder:
      type: string
      label: 'Placeholder'
    webform_id:
      type: string
      label: 'Webform ID'
    rows:
      type: integer
      label: 'Rows'
# see field.widget.settings.webform_entity_reference_autocomplete
# match_limit should already exist in schema but getting missing schema error.
#field.widget.settings.webform_entity_reference_autocomplete:
#  type: mapping
#  label: 'Webform Entity Reference Autocomplete Schema'
#  mapping:
#    match_limit:
#      type: integer
#      label: 'Match Limit'
